version: '3.9'

services:
  db:
    container_name: wsisz_java
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: communicator
      MYSQL_DATABASE: communicator
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d






  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1